/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package student;

public class App {
    public static void main(String[] args) {
        System.out.println("und so andere Sachen");
        Position pos1;
        Position pos2;

        System.out.println("=> test 1");
        pos1 = new Position("h8");
        pos2 = new Position(7, 7);

        System.out.println(pos1.toString());
        System.out.println(pos2.toString());
        System.out.println(pos1.equals(pos2));

        System.out.println("=> test 2");
        pos1 = new Position("a1");
        pos2 = new Position(0, 0);

        System.out.println(pos1.toString());
        System.out.println(pos2.toString());
        System.out.println(pos1.equals(pos2));
    }
}
