/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package student;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // default constructor test
        Chessboard cb;
        cb = new Chessboard();
        // cb.print();

        // get pos test
        Position pos1;

        pos1 = new Position("a1");
        System.out.println(cb.getFigure(pos1));

        pos1 = new Position("b1");
        System.out.println(cb.getFigure(pos1));

        // free between test

        // should return false
        System.out.println(cb.isFreeBetween(new Position(0, 0), new Position(7, 0)));

        // should return true
        System.out.println(cb.isFreeBetween(new Position(0, 3), new Position(0, 3)));

        // main things
        Scanner sc = new Scanner(System.in);
        int counter = 0;
        while (true) {
            cb.print();
            String color = counter % 2 == 0 ? "white" : "black";
            System.out.print(color + " > ");

            String userInput = sc.nextLine();

            if (userInput.equals("q")) {
                break;
            }

            String split[] = userInput.split(" ");

            Position reqStart = new Position(split[0]);
            Position reqEnd = new Position(split[1]);

            Figure fg = cb.getFigure(reqStart);

            if ((fg.getBlack() && color.equals("black")) || (!fg.getBlack() &&
                    color.equals("white"))) {

                if (cb.move(reqStart, reqEnd)) {
                    System.out.println(
                            color + " | " + fg.getSymbol() + " " + fg.getLabel() + " " + reqStart + " -> " + reqEnd
                                    + "\n");
                    counter += 1;
                } else {
                    System.out.println("Move isn't legal");

                }

            } else {
                System.out.println("You can't move this figure\n");
            }
        }
        sc.close();
    }
}
